// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OperationPrime.Infrastructure.Data;

#nullable disable

namespace OperationPrime.Migrations
{
    [DbContext(typeof(OperationPrimeDbContext))]
    [Migration("20250726000658_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("OperationPrime.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AuditId");

                    b.HasIndex("IncidentId", "Timestamp")
                        .HasDatabaseName("IX_AuditLog_IncidentId_Timestamp");

                    b.ToTable("AuditLogEntries");
                });

            modelBuilder.Entity("OperationPrime.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedApplication")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("Impact")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IncidentDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNoiSent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NoiSentDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationEmails")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupportTeam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Urgency")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Incidents");

                    b.HasDiscriminator().HasValue("Incident");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OperationPrime.Domain.Entities.MajorIncident", b =>
                {
                    b.HasBaseType("OperationPrime.Domain.Entities.Incident");

                    b.Property<int>("AffectedUsersCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BridgeDetails")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessImpact")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStatusUpdate")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DowntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EscalatedFromPreIncidentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedResolutionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentCommander")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCustomerFacing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPirCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPirRequired")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastStatusUpdateDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LessonsLearned")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PirScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootCause")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("MajorIncident");
                });

            modelBuilder.Entity("OperationPrime.Domain.Entities.PreIncident", b =>
                {
                    b.HasBaseType("OperationPrime.Domain.Entities.Incident");

                    b.Property<DateTime?>("EscalatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EscalatedToIncidentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PotentialImpact")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreventiveActions")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskAssessment")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("PreIncident");
                });
#pragma warning restore 612, 618
        }
    }
}
